Config from environment
statisticsnorway/microdata-datastore-builder pull request #45
Opened 2021-11-05 12:52 UTC by DanielElisenberg

# CONFIG FROM ENVIRONMENT
* Read config from environment
* Update config tests
* Refactor codebase to adjust to new config
* We can now configure a datastore-builder for a given datastore by passing it an env file when running the docker container with the '--env-file' flag

2021-11-05 14:11 UTC, vaskalan requested changes
dataset_import.get_user_input må tilpasses slik at datastore IKKE skal være en valgfri parameter.
CLI'en blir nå altså endret fra
`dataset_import.py -m <metadata_file> -d <data_file> -s <datastore>`
til
`dataset_import.py -m <metadata_file> -d <data_file>`

2021-11-08 07:16 UTC, pawbu commented
Looks good!

2021-11-08 08:15 UTC, vaskalan commented on README.md
>  poetry run python datastore_builder/dataset_import.py -m KREFTREG_DS.json -d KREFTREG_DS.csv -s KREFTREG
"-s KREFTREG" må fjernes her, ikke nødvendig lenger

2021-11-08 10:56 UTC, vaskalan approved these changes

2021-11-08 11:02 UTC, merged