Metadata service connection
statisticsnorway/microdata-datastore-builder pull request #53
Opened 2021-12-03 12:56 UTC by DanielElisenberg

# METADATA SERVICE CONNECTION
Service class for connection to metadata-service.

## Why?
In order to implement versioning the dataset-builder needs a connection to metadata-service.

## How?
* Implemented service class
    * Added requests as dependency
* Added unit test
    * Added requests-mock dependency
* Updated configuration module

2021-12-03 15:04 UTC, pawbu approved these changes

2021-12-03 15:04 UTC, pawbu commented on datastore_builder/service/metadata_service.py
> +            raise MetadataServiceError(
Maybe log the body of response?

2021-12-03 16:26 UTC, DanielElisenberg commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
Good point! 🙌🏻  But I am worried about that conceptually, though. There will essentially be no check for using the same variable name as a previously deleted variable in this case. Should we include a section on deleted variables in the metadata_all ? 🤔

2021-12-06 07:39 UTC, pawbu commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
We will have this information in data_store.json (/metadata/data-store endpoint). For each version we know the operation type (REMOVE, ADD etc.).

2021-12-06 07:57 UTC, DanielElisenberg commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
Then should we check if a variable of that name has been previously REMOVEd? That seems necessary. We do a request to fetch data_store.json for the sake of version already, so it should be fairly easy to add this check.

2021-12-06 08:30 UTC, pawbu commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
I don't think so. We only need to know if the dataset is a part of the newest data store version. If it isn't then it's irrelevant if it has been deleted previously or never appeared.

2021-12-06 08:33 UTC, pawbu commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
OK, see you're asking about the algorithm after we get the response from metadata-service. If we want to behold today's functionality, then yes, we need to check if the dataset has been deleted and not allow to add it again. Maybe it would now be possible to have this opportunity, but we need to think what other consequences that might have.

2021-12-06 08:35 UTC, DanielElisenberg commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
Let's have a team chat about it before I merge 👍🏻

2021-12-06 08:35 UTC, pawbu commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
Sounds good!

2021-12-06 08:50 UTC, vaskalan commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
I believe metadata-all json for a given versjon (current or persistent) should only include the datasets for this actual versjon. 
A current metadata-all should include all RELEASED, PENDING_*, DRAFT.
A persistent metadata-all (i.e. 10.1.5) should include all released datasets in this versjon as well as datasets released in all previous versions.
Deleted datasets will appear in response from /metadata/data-store with operation type = REMOVE, as Pawel mentions.
I dont think we will need to track a dataset backwards on a list of datastore versions at any point, as we do in M1.5
Lets talk about this in the meeting later today.

2021-12-06 10:30 UTC, pawbu commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
According to a discussong we have had (we can take a look at the table) metadata_all_0_0_0.json will include DRAFT and PEDING_*. There will be metadata_all_x_x_x.json for each released version.

2021-12-06 10:32 UTC, vaskalan commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
Agree! current metadata-all = metadata_all_0_0_0.json

2021-12-06 10:36 UTC, DanielElisenberg commented on datastore_builder/service/metadata_service.py
> +            metadata["name"] == dataset_name
It would be easy to write a function that takes the data_store.json dict and picks out all dataset_names that have been REMOVEd at some point. Then simply returning an error message to user that this variable name has already been used.

As for whether we should do the metadata_all lookup in metadata_all__0_0_0.json or the latest released version, i think the metadata_all__0_0_0.json sounds the most reasonable. (considering we can also check for overwriting existing draft)
The latter can easily be hard coded, if that's the solution we end up with 😃

2021-12-09 09:28 UTC, DanielElisenberg commented on dataset_builder/adapter/metadata_service_adapter.py
> +    def get_dataset_status(self, dataset_name: str) -> dict:
Leverer tilbake status dict, men tom dict om dataset ikke eksisterer i kodebasen.
Tanker om å gjøre dette fremfor å f.eks. kaste en error?

2021-12-09 09:30 UTC, DanielElisenberg commented on dataset_builder/add_dataset.py
> +def allowed_add_operation(dataset_name: str, metadata_service_url: str) -> bool:
Hvis dataset ikke eksisterer **eller** eksisterer som ADD i draft er det allowed å gjør en "add_dataset" command.
Når vi samler dette i en commands.py-modul tenker jeg å legge til en "overwrite_draft" toggle

2021-12-09 09:31 UTC, DanielElisenberg commented
@pawbu @vaskalan 
Oppdaterte adapteret for å matche det nye endepunktet implementert i metadata-service.

2021-12-09 13:15 UTC, vaskalan commented on dataset_builder/adapter/metadata_service_adapter.py
> +    def get_metadata_all(self, semver: str) -> dict:
Why would dataset builder get metadata all?

2021-12-09 13:16 UTC, vaskalan commented on dataset_builder/adapter/metadata_service_adapter.py
> +    def get_dataset_status(self, dataset_name: str) -> dict:
I think an empty dict is fine.

2021-12-09 13:18 UTC, DanielElisenberg commented on dataset_builder/adapter/metadata_service_adapter.py
> +    def get_metadata_all(self, semver: str) -> dict:
It might not be necessary, but the thought was for the sake of getting the metadata the CHANGE pipeline where you want to validate the new data with existing metadata. This could be obtained from a specific data-structure endpoint though, so I can delete this function.

2021-12-09 13:19 UTC, vaskalan requested changes
Documentation please :-)
Hint : METADATA_SERVICE_URL

2021-12-09 14:02 UTC, vaskalan approved these changes

2021-12-09 14:21 UTC, merged